import React, { useState, useEffect } from 'react';
import {
  RefreshCw,
  AlertTriangle,
  Download,
  Shield,
  Activity
} from 'lucide-react';
import Button from '../ui/Button';
import Card from '../ui/Card';
import ThreatFeedWidget from './ThreatFeedWidget';
import ThreatStatsWidget from './ThreatStatsWidget';
import HealthcareBreachTracker from './HealthcareBreachTracker';
import {
  fetchAllFeeds,
  searchThreats,
  getThreatStatistics,
  type RSSItem,
  type AggregatedThreatData
} from '../../services/rssFeedService';
import {
  analyzeThreatTrends,
  calculateOrganizationRiskScore
} from '../../utils/ransomwareAnalyzer';
import {
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell
} from 'recharts';

interface ThreatStatistics {
  totalThreats: number;
  criticalThreats: number;
  recentThreats: number;
  trendDirection: 'up' | 'down' | 'stable';
}

interface ThreatTrend {
  direction: 'increasing' | 'decreasing' | 'stable';
  percentage: number;
  period: string;
}

interface RiskScore {
  score: number;
  level: 'critical' | 'high' | 'medium' | 'low';
  factors: string[];
}

interface RansomwareThreatDashboardProps {
  autoRefresh?: boolean;
  refreshInterval?: number;
}

const RansomwareThreatDashboard: React.FC<RansomwareThreatDashboardProps> = ({
  autoRefresh = true,
  refreshInterval = 300000 // 5 minutes
}) => {
  const [threatData, setThreatData] = useState<AggregatedThreatData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [stats, setStats] = useState<ThreatStatistics | null>(null);
  const [trend, setTrend] = useState<ThreatTrend | null>(null);
  const [riskScore, setRiskScore] = useState<RiskScore | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState<RSSItem[]>([]);

  useEffect(() => {
    loadThreatData();
    
    if (autoRefresh) {
      const interval = setInterval(loadThreatData, refreshInterval);
      return () => clearInterval(interval);
    }
  }, [autoRefresh, refreshInterval]);

  const loadThreatData = async () => {
    try {
      setIsLoading(true);
      setIsRefreshing(true);
      
      const [data, statsData] = await Promise.all([
        fetchAllFeeds(),
        getThreatStatistics()
      ]);
      
      setThreatData(data);
      setStats(statsData);
      
      if (data.items.length > 0) {
        const trendData = analyzeThreatTrends(data.items);
        setTrend(trendData);
        
        const riskData = calculateOrganizationRiskScore(data.items);
        setRiskScore(riskData);
      }
    } catch (error) {
      console.error('Failed to load threat data:', error);
    } finally {
      setIsLoading(false);
      setIsRefreshing(false);
    }
  };

  const handleSearch = async (query: string) => {
    if (!query.trim()) {
      setSearchResults([]);
      return;
    }

    try {
      const results = await searchThreats(query);
      setSearchResults(results);
    } catch (error) {
      console.error('Search failed:', error);
    }
  };

  const exportReport = () => {
    if (!threatData) return;
    
    const report = generateTextReport(threatData, stats, riskScore);
    const blob = new Blob([report], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `ransomware-threat-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const generateTextReport = (data: AggregatedThreatData, stats: any, risk: any) => {
    return `
RANSOMWARE THREAT INTELLIGENCE REPORT
Generated: ${new Date().toISOString()}

EXECUTIVE SUMMARY
================
Total Threats: ${stats?.totalThreats || 0}
Healthcare Breaches: ${stats?.healthcareBreaches || 0}
Critical Threats: ${stats?.criticalThreats || 0}
Organization Risk Score: ${risk?.score || 0}/100 (${risk?.level || 'N/A'})

THREAT STATISTICS
=================
High Priority Threats: ${stats?.criticalThreats + stats?.highThreats || 0}
Medium Threats: ${stats?.mediumThreats || 0}
Low Threats: ${stats?.lowThreats || 0}

Last 24 Hours: ${stats?.last24Hours || 0} new threats
Last 7 Days: ${stats?.last7Days || 0} total threats

RECENT HEALTHCARE BREACHES
==========================
${data.healthcareBreaches.slice(0, 10).map((item, idx) => `
${idx + 1}. ${item.title}
   Severity: ${item.severity || 'Unknown'}
   Published: ${item.pubDate}
   Link: ${item.link}
`).join('')}

CRITICAL THREATS
================
${data.criticalThreats.slice(0, 10).map((item, idx) => `
${idx + 1}. ${item.title}
   Severity: ${item.severity || 'Unknown'}
   Published: ${item.pubDate}
   Link: ${item.link}
`).join('')}

DATA SOURCES
============
${data.sources.join('\n')}

Report generated by MediSoluce Ransomware Threat Intelligence Dashboard
`;
  };

  if (isLoading) {
    return (
      <div className="py-12">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-7xl mx-auto">
            <div className="text-center">
              <RefreshCw className="h-12 w-12 animate-spin text-primary-500 mx-auto mb-4" />
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
                Loading Threat Intelligence...
              </h2>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (!threatData) {
    return (
      <div className="py-12">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-7xl mx-auto text-center">
            <AlertTriangle className="h-16 w-16 text-yellow-500 mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
              Failed to Load Threat Data
            </h2>
            <Button onClick={loadThreatData}>
              Retry
            </Button>
          </div>
        </div>
      </div>
    );
  }

  // Prepare chart data
  const severityDistribution = threatData ? [
    { name: 'Critical', value: stats?.criticalThreats || 0, fill: '#dc3545' },
    { name: 'High', value: stats?.highThreats || 0, fill: '#fd7e14' },
    { name: 'Medium', value: stats?.mediumThreats || 0, fill: '#ffc107' },
    { name: 'Low', value: stats?.lowThreats || 0, fill: '#6c757d' }
  ] : [];

  return (
    <div className="py-8">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          {/* Header */}
          <div className="mb-8">
            <div className="flex items-center justify-between flex-wrap gap-4">
              <div>
                <h1 className="text-3xl font-heading font-bold text-gray-900 dark:text-white mb-2">
                  Ransomware Threat Intelligence Dashboard
                </h1>
                <p className="text-gray-600 dark:text-gray-300">
                  Real-time monitoring of ransomware threats impacting healthcare organizations
                </p>
              </div>
              <div className="flex items-center space-x-3">
                <Button
                  variant="outline"
                  onClick={loadThreatData}
                  disabled={isRefreshing}
                  icon={isRefreshing ? <RefreshCw className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
                >
                  {isRefreshing ? 'Refreshing...' : 'Refresh'}
                </Button>
                <Button
                  onClick={exportReport}
                  icon={<Download className="h-4 w-4" />}
                >
                  Export Report
                </Button>
              </div>
            </div>

            {/* Risk Score Alert */}
            {riskScore && riskScore.level === 'critical' && (
              <div className="mt-4 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
                <div className="flex items-start">
                  <AlertTriangle className="h-6 w-6 text-red-600 dark:text-red-400 mr-3 mt-0.5" />
                  <div className="flex-1">
                    <h3 className="text-red-800 dark:text-red-200 font-semibold mb-2">
                      Critical Risk Level Detected
                    </h3>
                    <p className="text-red-700 dark:text-red-300 text-sm mb-3">
                      Your organization's risk score is {riskScore.score}/100. Immediate action recommended.
                    </p>
                    <div className="space-y-2">
                      {riskScore.factors.map((factor: any, idx: number) => (
                        <div key={idx} className="text-sm text-red-700 dark:text-red-300">
                          • {factor.factor} ({factor.severity})
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Search Bar */}
          <div className="mb-8">
            <div className="flex items-center space-x-3">
              <div className="flex-1 relative">
                <input
                  type="text"
                  placeholder="Search threats..."
                  value={searchQuery}
                  onChange={(e) => {
                    setSearchQuery(e.target.value);
                    handleSearch(e.target.value);
                  }}
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white"
                />
              </div>
            </div>
            {searchResults.length > 0 && (
              <div className="mt-4 p-4 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg">
                <p className="text-sm text-blue-700 dark:text-blue-300 mb-2">
                  Found {searchResults.length} matching threats
                </p>
              </div>
            )}
          </div>

          {/* Stats Overview */}
          {stats && <ThreatStatsWidget stats={stats} trend={trend} />}

          {/* Charts Section */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
            {/* Severity Distribution Pie Chart */}
            <Card className="p-6">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-6">
                Threat Severity Distribution
              </h3>
              <div className="h-80">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={severityDistribution}
                      cx="50%"
                      cy="50%"
                      labelLine={false}
                      label={({ name, percent }) => `${name}: ${(percent * 100).toFixed(0)}%`}
                      outerRadius={100}
                      fill="#8884d8"
                      dataKey="value"
                    >
                      {severityDistribution.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.fill} />
                      ))}
                    </Pie>
                    <Tooltip />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </Card>

            {/* Threat Activity Over Time */}
            <Card className="p-6">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-6">
                Threat Activity (Last 7 Days)
              </h3>
              <div className="h-80 flex items-center justify-center text-gray-500 dark:text-gray-400">
                <div className="text-center">
                  <Activity className="h-12 w-12 mx-auto mb-4 opacity-50" />
                  <p>Chart data available after collection period</p>
                </div>
              </div>
            </Card>
          </div>

          {/* Threat Feeds */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
            <ThreatFeedWidget
              threats={threatData.recentThreats}
              title="Recent Threat Intelligence"
              maxItems={15}
            />
            <ThreatFeedWidget
              threats={threatData.criticalThreats}
              title="Critical Threats"
              maxItems={10}
            />
          </div>

          {/* Healthcare Breach Tracker */}
          <div className="mb-8">
            <HealthcareBreachTracker
              breaches={threatData.healthcareBreaches}
              maxItems={10}
            />
          </div>

          {/* Data Sources Info */}
          <Card className="p-6">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
              Data Sources
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {threatData.sources.map((source, idx) => (
                <div key={idx} className="flex items-center space-x-2 p-3 bg-gray-50 dark:bg-gray-800 rounded-lg">
                  <Shield className="h-4 w-4 text-primary-500" />
                  <span className="text-sm text-gray-900 dark:text-white">{source}</span>
                </div>
              ))}
            </div>
            <div className="mt-4 text-xs text-gray-500 dark:text-gray-400">
              Last updated: {threatData.lastUpdated.toLocaleString()}
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default RansomwareThreatDashboard;

