import React from 'react';
import { accessibilityEnhancer } from '../../utils/accessibilityEnhancer';

// Accessibility Testing Utilities
export const AccessibilityTester = {
  
  // Test component for accessibility violations
  testComponent: (component: React.ReactElement): Promise<{
    violations: any[];
    warnings: string[];
    score: number;
  }> => {
    return new Promise((resolve) => {
      // Mock accessibility testing (in real implementation, use axe-core)
      const violations: any[] = [];
      const warnings: string[] = [];
      
      // Check for common accessibility issues
      const element = document.createElement('div');
      document.body.appendChild(element);
      
      try {
        // Test for missing alt text
        const images = element.querySelectorAll('img');
        images.forEach((img, index) => {
          if (!img.getAttribute('alt')) {
            violations.push({
              id: 'image-alt',
              impact: 'serious',
              description: 'Images must have alt text',
              nodes: [img],
              help: 'Add alt text to images'
            });
          }
        });
        
        // Test for missing form labels
        const inputs = element.querySelectorAll('input, select, textarea');
        inputs.forEach((input) => {
          const id = input.getAttribute('id');
          const label = element.querySelector(`label[for="${id}"]`);
          const ariaLabel = input.getAttribute('aria-label');
          const ariaLabelledBy = input.getAttribute('aria-labelledby');
          
          if (!label && !ariaLabel && !ariaLabelledBy) {
            violations.push({
              id: 'label',
              impact: 'serious',
              description: 'Form elements must have labels',
              nodes: [input],
              help: 'Add labels to form elements'
            });
          }
        });
        
        // Test for proper heading hierarchy
        const headings = element.querySelectorAll('h1, h2, h3, h4, h5, h6');
        let h1Count = 0;
        headings.forEach((heading) => {
          if (heading.tagName === 'H1') {
            h1Count++;
          }
        });
        
        if (h1Count === 0) {
          violations.push({
            id: 'page-has-heading-one',
            impact: 'moderate',
            description: 'Page must have a level 1 heading',
            nodes: [],
            help: 'Add an H1 heading to the page'
          });
        } else if (h1Count > 1) {
          violations.push({
            id: 'page-has-one-main',
            impact: 'moderate',
            description: 'Page should have only one H1 heading',
            nodes: [],
            help: 'Use only one H1 heading per page'
          });
        }
        
        // Test for keyboard accessibility
        const interactiveElements = element.querySelectorAll('button, a, input, select, textarea, [tabindex]');
        interactiveElements.forEach((element) => {
          const tabIndex = element.getAttribute('tabindex');
          if (tabIndex === '-1' && element.getAttribute('role') !== 'presentation') {
            warnings.push('Interactive element has negative tabindex');
          }
        });
        
        // Calculate accessibility score
        const totalChecks = 10; // Total number of checks performed
        const violationCount = violations.length;
        const score = Math.max(0, Math.round(((totalChecks - violationCount) / totalChecks) * 100));
        
        resolve({
          violations,
          warnings,
          score
        });
        
      } finally {
        document.body.removeChild(element);
      }
    });
  },
  
  // Generate accessibility report
  generateReport: (testResults: {
    violations: any[];
    warnings: string[];
    score: number;
  }) => {
    const { violations, warnings, score } = testResults;
    
    const report = `
ACCESSIBILITY TEST REPORT
Generated: ${new Date().toLocaleString()}

OVERALL SCORE: ${score}/100

VIOLATIONS FOUND: ${violations.length}
${violations.map((violation, index) => `
${index + 1}. ${violation.description}
   Impact: ${violation.impact}
   Help: ${violation.help}
`).join('')}

WARNINGS: ${warnings.length}
${warnings.map((warning, index) => `${index + 1}. ${warning}`).join('\n')}

RECOMMENDATIONS:
${violations.length === 0 ? '✅ No accessibility violations found!' : '❌ Please address the violations listed above.'}
${warnings.length > 0 ? '⚠️ Consider addressing the warnings for better accessibility.' : ''}

This report was generated by MediSoluce Accessibility Tester.
For more information, visit: https://www.w3.org/WAI/WCAG21/quickref/
    `;
    
    return report;
  },
  
  // Test specific accessibility features
  testFeature: (feature: 'keyboard' | 'screen-reader' | 'color-contrast' | 'focus-management') => {
    switch (feature) {
      case 'keyboard':
        return AccessibilityTester.testKeyboardNavigation();
      case 'screen-reader':
        return AccessibilityTester.testScreenReaderSupport();
      case 'color-contrast':
        return AccessibilityTester.testColorContrast();
      case 'focus-management':
        return AccessibilityTester.testFocusManagement();
      default:
        throw new Error(`Unknown accessibility feature: ${feature}`);
    }
  },
  
  // Test keyboard navigation
  testKeyboardNavigation: () => {
    const focusableElements = document.querySelectorAll(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
    );
    
    const issues = [];
    
    focusableElements.forEach((element) => {
      // Test if element can receive focus
      (element as HTMLElement).focus();
      if (document.activeElement !== element) {
        issues.push(`Element cannot receive focus: ${element.tagName}`);
      }
      
      // Test for visible focus indicators
      const computedStyle = window.getComputedStyle(element);
      const outline = computedStyle.outline;
      const boxShadow = computedStyle.boxShadow;
      
      if (outline === 'none' && !boxShadow.includes('rgb')) {
        issues.push(`Element lacks visible focus indicator: ${element.tagName}`);
      }
    });
    
    return {
      totalElements: focusableElements.length,
      issues,
      score: Math.max(0, 100 - (issues.length * 10))
    };
  },
  
  // Test screen reader support
  testScreenReaderSupport: () => {
    const issues = [];
    
    // Check for proper ARIA labels
    const elementsWithRole = document.querySelectorAll('[role]');
    elementsWithRole.forEach((element) => {
      const role = element.getAttribute('role');
      const ariaLabel = element.getAttribute('aria-label');
      const ariaLabelledBy = element.getAttribute('aria-labelledby');
      
      if (!ariaLabel && !ariaLabelledBy && !element.textContent?.trim()) {
        issues.push(`Element with role "${role}" lacks accessible name`);
      }
    });
    
    // Check for proper heading structure
    const headings = document.querySelectorAll('h1, h2, h3, h4, h5, h6');
    const headingLevels = Array.from(headings).map(h => parseInt(h.tagName.substring(1)));
    
    for (let i = 1; i < headingLevels.length; i++) {
      if (headingLevels[i] > headingLevels[i - 1] + 1) {
        issues.push(`Heading hierarchy skip: H${headingLevels[i - 1]} to H${headingLevels[i]}`);
      }
    }
    
    return {
      totalElements: elementsWithRole.length,
      issues,
      score: Math.max(0, 100 - (issues.length * 15))
    };
  },
  
  // Test color contrast
  testColorContrast: () => {
    const issues = [];
    const textElements = document.querySelectorAll('p, h1, h2, h3, h4, h5, h6, span, div');
    
    // Sample first 20 elements to avoid performance issues
    Array.from(textElements).slice(0, 20).forEach((element) => {
      const style = window.getComputedStyle(element);
      const textColor = style.color;
      const backgroundColor = style.backgroundColor;
      
      // Simple contrast check (in production, use proper contrast calculation)
      if (textColor && backgroundColor && textColor === backgroundColor) {
        issues.push(`Element may have insufficient color contrast: ${element.tagName}`);
      }
    });
    
    return {
      elementsChecked: Math.min(textElements.length, 20),
      issues,
      score: Math.max(0, 100 - (issues.length * 20))
    };
  },
  
  // Test focus management
  testFocusManagement: () => {
    const issues = [];
    
    // Check for focus traps in modals
    const modals = document.querySelectorAll('[role="dialog"]');
    modals.forEach((modal) => {
      const focusableElements = modal.querySelectorAll(
        'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
      );
      
      if (focusableElements.length === 0) {
        issues.push('Modal lacks focusable elements');
      }
    });
    
    // Check for skip links
    const skipLinks = document.querySelectorAll('a[href^="#"]');
    if (skipLinks.length === 0) {
      issues.push('Page lacks skip links for keyboard navigation');
    }
    
    return {
      modalsChecked: modals.length,
      issues,
      score: Math.max(0, 100 - (issues.length * 25))
    };
  }
};

// React component for accessibility testing
interface AccessibilityTestProps {
  children: React.ReactNode;
  onTestComplete?: (results: any) => void;
  autoTest?: boolean;
}

export const AccessibilityTestWrapper: React.FC<AccessibilityTestProps> = ({
  children,
  onTestComplete,
  autoTest = false
}) => {
  const [testResults, setTestResults] = React.useState<any>(null);
  const [isTesting, setIsTesting] = React.useState(false);
  
  const runTests = async () => {
    setIsTesting(true);
    
    try {
      const results = await AccessibilityTester.testComponent(
        React.createElement('div', {}, children)
      );
      
      setTestResults(results);
      
      if (onTestComplete) {
        onTestComplete(results);
      }
      
      // Announce results to screen reader
      accessibilityEnhancer.announceToScreenReader(
        `Accessibility test completed. Score: ${results.score} out of 100. ${results.violations.length} violations found.`
      );
      
    } catch (error) {
      console.error('Accessibility test failed:', error);
    } finally {
      setIsTesting(false);
    }
  };
  
  React.useEffect(() => {
    if (autoTest) {
      runTests();
    }
  }, [autoTest]);
  
  return (
    <div>
      {children}
      
      {!import.meta.env.PROD && (
        <div className="fixed bottom-4 left-4 z-50">
          <button
            onClick={runTests}
            disabled={isTesting}
            className="bg-primary-600 text-white px-4 py-2 rounded-lg shadow-lg hover:bg-primary-700 disabled:opacity-50"
            aria-label="Run accessibility tests"
          >
            {isTesting ? 'Testing...' : 'Test A11y'}
          </button>
          
          {testResults && (
            <div className="mt-2 p-4 bg-white dark:bg-gray-800 rounded-lg shadow-lg max-w-sm">
              <h3 className="font-semibold mb-2">Accessibility Score: {testResults.score}/100</h3>
              <p className="text-sm text-gray-600 dark:text-gray-300">
                {testResults.violations.length} violations, {testResults.warnings.length} warnings
              </p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default AccessibilityTester;

