// Profile management utilities

export interface UserProfile {
  id: string;
  email: string;
  name: string;
  organization: string;
  role: string;
  industry: string;
  certifications: string[];
  preferences: ProfilePreferences;
  avatar?: string;
  timezone: string;
  phone_number?: string;
  department?: string;
  manager?: string;
  created_at: string;
  updated_at: string;
  current_organization_id?: string;
}

export interface ProfilePreferences {
  theme: 'light' | 'dark';
  autoSave: boolean;
  language: string;
  reportFormat: 'detailed' | 'summary';
  defaultFramework: string | null;
  emailNotifications: boolean;
  assessmentReminders: boolean;
  defaultReportSections: string[];
  showGuidanceByDefault: boolean;
}

export const defaultPreferences: ProfilePreferences = {
  theme: 'light',
  autoSave: true,
  language: 'en',
  reportFormat: 'detailed',
  defaultFramework: null,
  emailNotifications: false,
  assessmentReminders: true,
  defaultReportSections: [],
  showGuidanceByDefault: true
};

export const createDefaultProfile = (userId: string, email: string): UserProfile => {
  return {
    id: userId,
    email,
    name: '',
    organization: '',
    role: '',
    industry: '',
    certifications: [],
    preferences: { ...defaultPreferences },
    timezone: 'UTC',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  };
};

export const validateProfileData = (profile: Partial<UserProfile>): { isValid: boolean; errors: string[] } => {
  const errors: string[] = [];

  if (!profile.email) {
    errors.push('Email is required');
  }

  if (profile.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(profile.email)) {
    errors.push('Invalid email format');
  }

  if (profile.phone_number && !/^\+?[\d\s\-()]{10,}$/.test(profile.phone_number)) {
    errors.push('Invalid phone number format');
  }

  return {
    isValid: errors.length === 0,
    errors
  };
};

export const formatCertifications = (certifications: string[]): string => {
  if (!certifications || certifications.length === 0) return '';
  return certifications.join(', ');
};

export const parseCertifications = (certificationsString: string): string[] => {
  if (!certificationsString) return [];
  return certificationsString
    .split(',')
    .map(cert => cert.trim())
    .filter(cert => cert.length > 0);
};

export const getProfileCompleteness = (profile: UserProfile): { percentage: number; missingFields: string[] } => {
  const requiredFields = ['name', 'organization', 'role'];
  const optionalFields = ['industry', 'department', 'phone_number', 'certifications'];
  
  const allFields = [...requiredFields, ...optionalFields];
  const completedFields = allFields.filter(field => {
    const value = profile[field as keyof UserProfile];
    return value && (Array.isArray(value) ? value.length > 0 : String(value).trim().length > 0);
  });

  const missingRequired = requiredFields.filter(field => {
    const value = profile[field as keyof UserProfile];
    return !value || String(value).trim().length === 0;
  });

  const percentage = Math.round((completedFields.length / allFields.length) * 100);

  return {
    percentage,
    missingFields: missingRequired
  };
};

export const exportProfile = (profile: UserProfile): string => {
  const completeness = getProfileCompleteness(profile);
  
  return `
MEDISOLUCE USER PROFILE EXPORT
Generated: ${new Date().toLocaleString()}

PERSONAL INFORMATION:
- Name: ${profile.name || 'Not set'}
- Email: ${profile.email}
- Phone: ${profile.phone_number || 'Not set'}
- Timezone: ${profile.timezone}

PROFESSIONAL INFORMATION:
- Organization: ${profile.organization || 'Not set'}
- Role/Title: ${profile.role || 'Not set'}
- Industry: ${profile.industry || 'Not set'}
- Department: ${profile.department || 'Not set'}
- Manager: ${profile.manager || 'Not set'}
- Certifications: ${formatCertifications(profile.certifications) || 'None'}

PREFERENCES:
- Theme: ${profile.preferences.theme}
- Language: ${profile.preferences.language}
- Report Format: ${profile.preferences.reportFormat}
- Auto-save: ${profile.preferences.autoSave ? 'Enabled' : 'Disabled'}
- Assessment Reminders: ${profile.preferences.assessmentReminders ? 'Enabled' : 'Disabled'}
- Email Notifications: ${profile.preferences.emailNotifications ? 'Enabled' : 'Disabled'}
- Show Guidance: ${profile.preferences.showGuidanceByDefault ? 'Enabled' : 'Disabled'}

ACCOUNT INFORMATION:
- Profile Completeness: ${completeness.percentage}%
- Account Created: ${new Date(profile.created_at).toLocaleString()}
- Last Updated: ${new Date(profile.updated_at).toLocaleString()}
- Missing Fields: ${completeness.missingFields.length > 0 ? completeness.missingFields.join(', ') : 'None'}

Generated by MediSoluce Healthcare Compliance Platform
`;
};

// Profile analytics utilities
export const trackProfileEvent = (eventType: 'viewed' | 'updated' | 'completed', details?: any) => {
  if (typeof window !== 'undefined' && (window as any).gtag) {
    (window as any).gtag('event', `profile_${eventType}`, {
      event_category: 'User Profile',
      event_label: eventType,
      custom_parameter: details
    });
  }
};

export const getProfileInsights = (profile: UserProfile) => {
  const completeness = getProfileCompleteness(profile);
  const insights: string[] = [];

  if (completeness.percentage < 50) {
    insights.push('Complete your profile to get personalized recommendations');
  }

  if (!profile.organization) {
    insights.push('Add your organization to access organization-specific features');
  }

  if (!profile.role) {
    insights.push('Specify your role to receive relevant compliance guidance');
  }

  if (profile.certifications.length === 0) {
    insights.push('Add your certifications to showcase your expertise');
  }

  if (!profile.preferences.assessmentReminders) {
    insights.push('Enable assessment reminders to stay compliant');
  }

  return insights;
};