import React from 'react';
import { FileText, File, Database } from 'lucide-react';
import Button from '../ui/Button';
import { analytics } from '../../utils/analytics';

interface ExportManagerProps {
  data: Record<string, unknown>[];
  filename: string;
  title?: string;
}

const ExportManager: React.FC<ExportManagerProps> = ({ data, filename, title }) => {
  const exportToJSON = () => {
    const jsonData = JSON.stringify(data, null, 2);
    downloadFile(jsonData, `${filename}.json`, 'application/json');
    analytics.trackDownload(`${filename} JSON Export`, 'JSON');
  };

  const exportToCSV = () => {
    if (data.length === 0) return;
    
    const headers = Object.keys(data[0]).join(',');
    const rows = data.map(row => 
      Object.values(row).map(value => {
        const stringValue = String(value);
        return stringValue.includes(',') ? `"${stringValue}"` : stringValue;
      }).join(',')
    ).join('\n');
    
    const csvContent = `${headers}\n${rows}`;
    downloadFile(csvContent, `${filename}.csv`, 'text/csv');
    analytics.trackDownload(`${filename} CSV Export`, 'CSV');
  };

  const exportToReport = () => {
    const reportContent = generateReport(data, title || filename);
    downloadFile(reportContent, `${filename}-report.txt`, 'text/plain');
    analytics.trackDownload(`${filename} Report`, 'TXT');
  };

  const downloadFile = (content: string, fileName: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const generateReport = (data: Record<string, unknown>[], title: string) => {
    const timestamp = new Date().toISOString();
    const date = new Date().toLocaleDateString();
    
    let report = `${title.toUpperCase()} REPORT\n`;
    report += `Generated: ${date}\n`;
    report += `Timestamp: ${timestamp}\n`;
    report += `Records: ${data.length}\n\n`;
    
    report += `SUMMARY\n`;
    report += `========\n`;
    
    if (data.length > 0) {
      const sampleKeys = Object.keys(data[0]);
      report += `Data fields: ${sampleKeys.join(', ')}\n\n`;
      
      report += `DETAILED DATA\n`;
      report += `=============\n\n`;
      
      data.forEach((item, index) => {
        report += `Record ${index + 1}:\n`;
        Object.entries(item).forEach(([key, value]) => {
          report += `  ${key}: ${value}\n`;
        });
        report += '\n';
      });
    } else {
      report += 'No data available\n\n';
    }
    
    report += `\nGenerated by MediSoluce Healthcare Compliance Platform\n`;
    report += `For support: support@medisoluce.com\n`;
    
    return report;
  };

  return (
    <div className="flex items-center space-x-2">
      <Button
        variant="outline"
        size="sm"
        onClick={exportToCSV}
        icon={<Database className="h-4 w-4" />}
        disabled={data.length === 0}
      >
        CSV
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={exportToJSON}
        icon={<File className="h-4 w-4" />}
        disabled={data.length === 0}
      >
        JSON
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={exportToReport}
        icon={<FileText className="h-4 w-4" />}
        disabled={data.length === 0}
      >
        Report
      </Button>
    </div>
  );
};

export default ExportManager;